### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by CanNotFlyFish** [yusangeng/ypackr#1]
我按照步骤来了一遍，报错了，错误如下：
D:\work\workDet\packr\packr>packr  -c=${2} -l=${1} -r=${https://DESKTOP-D1SM9OQ/svn/testProj/}

D:\work\workDet\packr\packr>node D:\work\workDet\packr\packr\\packr.js -c ${2} -l ${1} -r ${https://DESKTOP-D1SM9OQ/svn/testProj/}
module.js:340
    throw err;
    ^

Error: Cannot find module './misc'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\work\workDet\packr\packr\lib\cp.js:7:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\work\workDet\packr\packr\packr.js:13:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)

我看了下 lib下没有misc 这样的模块，请问这个怎么解决啊？

**Comment by yusangeng** [comment]
抱歉这个项目平时不在这个repo管理，导致上传出现了错误，我会更新一下。

**Comment by yusangeng** [comment]
已经更新
